services:
  wordpress:
    container_name: wordpress
    build: ./wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - network1
    restart: always
  mariadb:
    container_name: mariadb
    build: ./mariadb/.
    image: mariadb:10.4
    volumes:
      - mariadb_volume:/var/lib/mysqld
    env_file:
      - .env
    networks:
      - network1
    restart: always

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/bkotwica/Inception/wordpressv
      o: bind
      type: none
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/bkotwica/Inception/mariadbv
      o: bind
      type: none

networks:
  network1:
    name: network1
    driver: bridge
