services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/.
    image: mariadb:10.4
    volumes:
      - mariadb_volume:/var/lib/mysqld
    env_file:
      - .env
    networks:
      - mariadb_network
    restart: always

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
            device: /home/bkotwica/Inception/mariadb
            o: bind
            type: none

networks:
  mariadb_network:
    driver: bridge
