services:
  mariadb:
    image: mariadb:11.1
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=my_db
      - MARIADB_USER=bkotwica
      - MARIADB_PASSWORD=bkotwica
    volumes:
      - mariadb_volume:/var/lib/mariadb
    networks:
      - mariadb_network
    ports:
      - 3307:3306

volumes:
  mariadb_volume:

networks:
  mariadb_network:
    driver: bridge
