version: '2.29.7'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=password
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
